name: Compile and Run Java

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Compile Java
      run: |
        mkdir -p bin # Tạo thư mục để lưu trữ các file .class sau khi biên dịch
        javac -d bin $(find src -name '*.java') # Tìm và biên dịch tất cả các file .java trong thư mục src

    - name: Run Java
      run: java -cp src Main
